# Generated by Django 4.2 on 2026-07-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payee_payer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('DIRECT_DEBIT', 'Direct Debit'), ('STANDING_ORDER', 'Standing Order'), ('CARD_PAYMENT', 'Card Payment'), ('ATM_WITHDRAWAL', 'ATM Withdrawal'), ('FEE_CHARGE', 'Fee/Charge')], max_length=20),
        ),
    ]