source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "webrick"
gem "minima", "~> 2.5"

group :jekyll_plugins do
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-feed"
end
